[package]
name = "es-bench"
version = "0.1.0"
edition = "2021"

[features]
# Do NOT include "foundationdb" in the default list
default = []
umadb = ["dep:umadb-adapter"]
tephra = ["dep:tephra-adapter"]
kurrentdb = ["dep:kurrentdb-adapter"]
axonserver = ["dep:axonserver-adapter"]
eventsourcingdb = ["dep:eventsourcingdb-adapter"]
fact = ["dep:fact-adapter"]
marten = ["dep:marten-adapter"]
postgres-dcb-ttcte = ["dep:postgres-dcb-ttcte-adapter"]
foundationdb-dcb = ["dep:foundationdb-dcb-adapter"]

[dependencies]
anyhow = "1"
bench-core = { path = "../bench-core" }
bench-testcontainers = { path = "../testcontainers" }
chrono = "0.4"
clap = { version = "4", features = ["derive"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
serde_yaml = "0.9"
rand = "0.10"
tokio = { version = "1", features = ["rt-multi-thread", "macros", "signal"] }
tokio-util = { version = "0.7" }
#tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["fmt", "env-filter"] }

# Adapters
dummy-adapter = { path = "../adapters/dummy" }
umadb-adapter = { path = "../adapters/umadb", optional = true }
tephra-adapter = { path = "../adapters/tephra", optional = true }
kurrentdb-adapter = { path = "../adapters/kurrentdb", optional = true }
axonserver-adapter = { path = "../adapters/axonserver", optional = true }
eventsourcingdb-adapter = { path = "../adapters/eventsourcingdb", optional = true }
fact-adapter = { path = "../adapters/fact", optional = true }
marten-adapter = { path = "../adapters/marten", optional = true }
postgres-dcb-ttcte-adapter = { path = "../adapters/postgres-dcb-ttcte", optional = true }
foundationdb-dcb-adapter = { path = "../adapters/foundationdb-dcb", optional = true }
#marten-rs = { path = "../marten-rs" }
#postgres-dcb-ttcte = { path = "../postgres-dcb-ttcte" }
#tokio-postgres = "0.7"
